version: '3.8'

services:
  app:
    build: .
    tty: true
    stdin_open: true
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_DEVELOPMENT_URL: postgres://postgres:password@db:5432/app_development
      DATABASE_TEST_URL: postgres://postgres:password@db:5432/test
      REDIS_URL: redis://redis:6379/0

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      DATABASE_DEVELOPMENT_URL: postgres://postgres:password@db:5432/app_development
      REDIS_URL: redis://redis:6379/0

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_development
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    volumes:
      - redis:/data
    

volumes:
  pgdata:
  redis:
